import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.tree.ErrorNode;
import org.antlr.v4.runtime.tree.TerminalNode;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class SurveyTranslator implements SurveyGeneratorListener {
	public StringBuilder stringbuilder;
	public SurveyTranslator() {
		stringbuilder = new StringBuilder();
	}

	private String dequote(String somestring){
		return somestring.substring(1,somestring.length()-1);
	}

	@Override
	public void enterS(SurveyGeneratorParser.SContext ctx) {
		stringbuilder.append("\n" +
				"<!DOCTYPE html>\n" +
				"<html>\n" +
				"<head>\n" +
				"<title>Generated by SurveyGenerator</title>\n" +
				"    <style type=\"text/css\">\n" +
				"    .likert ul\n" +
				"    {\n" +
				"        list-style-type: none;\n" +
				"        margin: 0;\n" +
				"        padding: 0;\n" +
				"    }\n" +
				"\n" +
				"    .likert li\n" +
				"    {\n" +
				"        float: left;\n" +
				"        text-align: left;\n" +
				"        list-style-type: none;\n" +
				"    }\n" +
				"    </style>\n" +
				"</head>\n" +
				"<body>");
	}

	@Override
	public void exitS(SurveyGeneratorParser.SContext ctx) {
		stringbuilder.append("<br>\n" +
				"</body>\n" +
				"</html>");
	}

	@Override
	public void enterTitle(SurveyGeneratorParser.TitleContext ctx) {
		stringbuilder.append("<h1>" +
				dequote(ctx.getText()) +
				"</h1>" +
				"<br>");
	}

	@Override
	public void exitTitle(SurveyGeneratorParser.TitleContext ctx) {

	}

	@Override
	public void enterPage(SurveyGeneratorParser.PageContext ctx) {

	}

	@Override
	public void exitPage(SurveyGeneratorParser.PageContext ctx) {

	}

	@Override
	public void enterPagetitle(SurveyGeneratorParser.PagetitleContext ctx) {
		stringbuilder.append("<h2>" +
				dequote(ctx.getText()) +
				"</h2>" +
				"<br>");
	}

	@Override
	public void exitPagetitle(SurveyGeneratorParser.PagetitleContext ctx) {

	}

	@Override
	public void enterQtype(SurveyGeneratorParser.QtypeContext ctx) {

	}

	@Override
	public void exitQtype(SurveyGeneratorParser.QtypeContext ctx) {

	}

	@Override
	public void enterQuestion(SurveyGeneratorParser.QuestionContext ctx) {

	}

	@Override
	public void exitQuestion(SurveyGeneratorParser.QuestionContext ctx) {

	}

	@Override
	public void enterQuestiontitle(SurveyGeneratorParser.QuestiontitleContext ctx) {
		stringbuilder.append("<h3>" +
				dequote(ctx.getText()) +
				"</h3>" +
				"<br>");
	}

	@Override
	public void exitQuestiontitle(SurveyGeneratorParser.QuestiontitleContext ctx) {

	}

	@Override
	public void enterSubquestion(SurveyGeneratorParser.SubquestionContext ctx) {

	}

	@Override
	public void exitSubquestion(SurveyGeneratorParser.SubquestionContext ctx) {

	}

	@Override
	public void enterMulti(SurveyGeneratorParser.MultiContext ctx) {
		stringbuilder.append("<form>");

	}

	@Override
	public void exitMulti(SurveyGeneratorParser.MultiContext ctx) {
		stringbuilder.append("</form>");
	}

	@Override
	public void enterMultiplechoiceoption(SurveyGeneratorParser.MultiplechoiceoptionContext ctx) {
		stringbuilder.append("<input type=\"checkbox\">" +
				dequote(ctx.getText()) +
				"<br>");
	}

	@Override
	public void exitMultiplechoiceoption(SurveyGeneratorParser.MultiplechoiceoptionContext ctx) {

	}

	@Override
	public void enterSingle(SurveyGeneratorParser.SingleContext ctx) {
		stringbuilder.append("<form>");
		System.out.println("do we ever reach here?");
	}

	@Override
	public void exitSingle(SurveyGeneratorParser.SingleContext ctx) {
		stringbuilder.append("</form>");
	}

	@Override
	public void enterSinglechoiceoption(SurveyGeneratorParser.SinglechoiceoptionContext ctx) {
		stringbuilder.append("<input type=\"radio\">" +
				dequote(ctx.getText()) +
				"<br>");
	}

	@Override
	public void exitSinglechoiceoption(SurveyGeneratorParser.SinglechoiceoptionContext ctx) {

	}

	@Override
	public void enterTextentry(SurveyGeneratorParser.TextentryContext ctx) {

	}

	@Override
	public void exitTextentry(SurveyGeneratorParser.TextentryContext ctx) {

	}

	@Override
	public void enterNumber(SurveyGeneratorParser.NumberContext ctx) {

	}

	@Override
	public void exitNumber(SurveyGeneratorParser.NumberContext ctx) {

	}

	@Override
	public void enterDate(SurveyGeneratorParser.DateContext ctx) {

	}

	@Override
	public void exitDate(SurveyGeneratorParser.DateContext ctx) {

	}

	@Override
	public void enterUpload(SurveyGeneratorParser.UploadContext ctx) {

	}

	@Override
	public void exitUpload(SurveyGeneratorParser.UploadContext ctx) {

	}

	@Override
	public void enterScale(SurveyGeneratorParser.ScaleContext ctx) {

	}

	@Override
	public void exitScale(SurveyGeneratorParser.ScaleContext ctx) {

	}

	@Override
	public void visitTerminal(TerminalNode terminalNode) {

	}

	@Override
	public void visitErrorNode(ErrorNode errorNode) {

	}

	@Override
	public void enterEveryRule(ParserRuleContext parserRuleContext) {

	}

	@Override
	public void exitEveryRule(ParserRuleContext parserRuleContext) {

	}
}
